stages:
    - test
    - deploy

image: registry.gitlab.com/ashadi-cc/rt-04:latest

variables:
    MYSQL_DATABASE: homestead
    MYSQL_ROOT_PASSWORD: secret
    DB_HOST: mysql
    DB_USERNAME: root

cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

unit_test:
    stage: test
    services:
        - mysql:5.7
    script:
        - cp .env.example .env
        - composer install
        - php artisan key:generate
        - php artisan migrate
        - vendor/bin/phpunit
    artifacts:
        paths:
            - vendor/
            - .env
        expire_in: 1 days
        when: always
    cache:
        paths:
            - vendor/

deploy_production:
    stage: deploy
    script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
    environment:
        name: production
        url: $PROD_SERVER
    when: manual
    only:
        - master