version: "3"
services: 
  #db
  db:
    image: mariadb
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=8juu88886hhh
      - MYSQL_DATABASE=rt4
    volumes: 
      - gmrdata:/var/lib/mysql
    # ports: 
    #   - "3307:3306"
      
  #app
  app:
    image: ashadicc/php-fpm
    restart: unless-stopped
    tty: true
    environment: 
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=rt4
      - DB_USERNAME=root
      - DB_PASSWORD=8juu88886hhh
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - ./docker-res/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #nginx web server
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports: 
      - "127.0.0.1:8000:80"
    volumes: 
      - ./:/var/www
      - ./docker-res/nginx:/etc/nginx/conf.d
    depends_on: 
      - db
      - app

#volumes
volumes:
    gmrdata:
